---
# Sets up misc. things required for the agent to control network-booted boards
- name: Install required apt packages
  apt:
    pkg:
      - apt-cacher-ng
      - python3-periphery
      - python3-pexpect
      - qemu-utils
      - u-boot-tools
    state: present

- name: Create TFTP server subdirectory writable by github action runner
  file:
    path: /srv/tftp/rock-ci
    state: directory
    owner: root
    group: "{{ ghaction_group }}"
    mode: "u=rwx,g=rwx,o=rx"

- name: Define DHCP settings for each board
  template:
    src: dhcp_board.conf.j2
    dest: /etc/dnsmasq.d/{{ board.name }}.conf
  loop: "{{ boards }}"
  loop_control:
    loop_var: board

- name: Store each board configuration in a file for Github Actions
  template:
    src: action_board.conf.j2
    dest: /opt/ghaction/board_{{ board.name }}.conf
  loop: "{{ boards }}"
  loop_control:
    loop_var: board

- name: Create directory for base Debian images
  file:
    path: /opt/ghaction/base_images
    state: directory
    owner: "{{ ghaction_user }}"
    group: "{{ ghaction_group }}"
    mode: "u=rwx,g=rx,o=rx"
